apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo
spec:
  replicas: 3
  template:
    metadata:
      labels:
        ver: green
    spec:
      containers:
      - name: demo-web
        $patch: delete
      - name: demo-stress
        image: busybox:1.36.1
        imagePullPolicy: IfNotPresent
        command: ['sh', '-c', 'exit 1']
