########################################
#                                      #
#         CRASH LOOP BACK OFF          #
#                                      #
########################################


apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: demo
resources:
  - ../../base

namePrefix: green-

patches:
  - path: deployment.yaml

