apiVersion: v1
kind: PersistentVolume
metadata:
  generateName: pv-
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  nfs:
    path: /home/WORK/kubernetes/VMs/nfs
    server: 192.168.122.1
