apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: demo-alert
  namespace: duyaccel-dev

spec:
  route:
    receiver: 'cluster-listener'
    groupBy: [namespace, app]
    groupInterval: 5m
    repeatInterval: 10m

  receivers:
    - name: cluster-listener
      webhookConfigs:
        - url: http://el-alert-listener.duyaccel-dev.svc.cluster.local:8080
          sendResolved: false
---
