apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: demo
resources:
  - ../../base

configMapGenerator:
  - name: index
    files:
    - index.html

commonLabels:
  version: blue

namePrefix: blue-
patches:
  - path: deployment.yaml
